extends Control
#FIGURE OUT THE OTHER CHARACTER 
#FIGURE OUT THE OTHER CHARACTER 
#FIGURE OUT THE OTHER CHARACTER 
func _on_character_1_pressed():
	get_tree().change_scene_to_file("res://scenes/Scene1GAME.tscn")
#FIGURE OUT THE OTHER CHARACTER 
#FIGURE OUT THE OTHER CHARACTER 
#FIGURE OUT THE OTHER CHARACTER 
#FIGURE OUT THE OTHER CHARACTER 
